<a href="https://colab.research.google.com/github/FadyGamilM/Deep-Learning-TensorFlow/blob/master/00_Intro_To_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Objectives**

### `Agenda`:
* basics of tensors.
* Getting Info from tensors.
* Manupulating and changing data into tensors.
* Tensors & NumPy
* Using @tf.function (a way to speed up a regular python function)
* Using GPUs with Tensorflow


> ## **Basics of Tensors**

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.6.0


>> ## **Creating tensors tf.constant()**
---

In [ ]:
# Create tensor using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# You can check the dimensions of your tensor by using .ndim
scalar.ndim

0

In [ ]:
# But we will need vectors tensors more than scalars
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Lets explore the shape of matrix tensor ..
matrix = tf.constant([ [1, 2, 3],
                       [1, 5, 9],
                       [8, 7, 3] ])
matrix.ndim

2

In [ ]:
n_dim_matrix = tf.constant([ [ [1, 2], [4, 5] ],
                            [ [7, 8], [10, 13] ] ])
n_dim_matrix.ndim

3

>> ## **Creating tensors using tf.variable()**
---


In [ ]:
changeable_tensor = tf.Variable([10, 7])
unChangeable_tensor = tf.constant([10, 7])

In [ ]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
unChangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

- **What is the Diff. between variable and constant tensors ?**

In [ ]:
# we can change the value of variable tesnors..
changeable_tensor[0].assign(5)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>

In [ ]:
# we can't change the value of constant tensors..
unChangeable_tensor[0].assign(3)
unChangeable_tensor

AttributeError: ignored

>> ## **Creating tensors using tf.random()**
---

In [ ]:
# Lets create two random tesnors
## ==> Actually they will be the same tensor as we set the same seed
rand1 = tf.random.Generator.from_seed(52)
# what randTensor.normal() does ??? 
# ==> it outputs random values from a normal distribution, normal distribution is a function that represents the bell graph 
rand1 = rand1.normal(shape=(3, 2))
rand1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.0034493 ,  0.20857747],
       [ 0.35700995,  1.0648885 ],
       [ 1.2432485 , -2.2173238 ]], dtype=float32)>

In [ ]:
rand2 = tf.random.Generator.from_seed(52)
rand2 = rand2.normal(shape=(3, 2))
rand2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.0034493 ,  0.20857747],
       [ 0.35700995,  1.0648885 ],
       [ 1.2432485 , -2.2173238 ]], dtype=float32)>

In [ ]:

# Lets see if the actually the same..
rand1 == rand2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

* **we will need to shuffle the order of our inputs.. how to do that?**

In [ ]:
not_shuffled = tf.constant([[1, 2],
                            [3, 6],
                            [9, 18]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  6],
       [ 9, 18]], dtype=int32)>

In [ ]:
# Lets Shuffle it
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9, 18],
       [ 3,  6],
       [ 1,  2]], dtype=int32)>

- **So we are on the same page that we have to shuffle our input -tensor form- data befor we pass it into the input layer of neural network**.
- **HINT: our input data and initial values for weights, must be re-producable, so the result of shuffle must be the same each time we train the model on it, so we have to set the seed at any specific number and stuck with it till we finish our model**.

In [ ]:
# If you run the following 3 lines any number of times, the result will be the same :D !
tf.random.set_seed(60)
shuffled_ReProducable = tf.random.shuffle(not_shuffled, seed=60)
shuffled_ReProducable

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9, 18],
       [ 1,  2],
       [ 3,  6]], dtype=int32)>

>> ## **Creating tensors from NumPy arrays**
---

In [ ]:
import numpy as np
# create numpy array .. 
A_np = np.arange(1, 25)
A_np ## ==> its a 1x24 (1 row and 24 cols) vector from NumPy array type..

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Lets convert it into tensor with any shape we want..
A_tf_1 = tf.constant(A_np, shape=(3, 8))
A_tf_1 = tf.Variable(A_tf_1)
A_tf_1
A_tf_1[0].assign([8,7,6,5,4,3,2,1])

<tf.Variable 'UnreadVariable' shape=(3, 8) dtype=int64, numpy=
array([[ 8,  7,  6,  5,  4,  3,  2,  1],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])>

* `Hey, I am here to say to you that you will need the following method later..`


In [ ]:
rank2_tf = tf.Variable([[1, 5, 9],[7, 5, 3]])
rank2_tf ## => Shape is 2 rows and 3 cols


<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 5, 9],
       [7, 5, 3]], dtype=int32)>

In [ ]:
# Lets Change the shape by adding a new shape at the end without changing any of rank2_tf content ..
rank3_tf = tf.expand_dims(rank2_tf, -1)
rank3_tf ## => Oh! now we have 2-rows, each row has 3-rows, each one of them has 1-col

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [5],
        [9]],

       [[7],
        [5],
        [3]]], dtype=int32)>

>> ## **Tensors Manipulation (Mathematical Operations)**
---



- **Tensors Addition** 

In [ ]:
t_original = tf.constant([[1, 2], [3, 4]])
t_original + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
# What about the original tensor
t_original

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# so it will never change unless you set it ..
t_original = t_original + 10
t_original

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

**IMPORTANT HINT**
>>> tensor library also has methods that perform these math. operations, so when to use the operators and when to use these built-in methods ?
- `Whenever you need your code to run faster on GPU, use tensor library version of whatever you want to do :D`



In [ ]:
t_original = tf.add(t_original, -10)
t_original # -> here we back to the original one 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

>> ## **Matrix Multiplication in tensorFlow**

-- what we talking about here is dot product

In [ ]:
# A with shape = 3*2 
# B with shape = 2*4
# Result C = A.B with shape = 3*4
A = tf.constant([
                 [10, 3],
                 [4, 5],
                 [6, 2]
                 ])
B = tf.constant([
                 [1, 2, 4, 5],
                 [3, 8, 6, 2]
                 ])
# make sure the shape is correctly 
A.shape, B.shape
# Create the result matrix C ..
C = tf.linalg.matmul(A, B)
C, C.shape

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[19, 44, 58, 56],
        [19, 48, 46, 30],
        [12, 28, 36, 34]], dtype=int32)>, TensorShape([3, 4]))

>> ## **Casting data type of tensors**
---



In [ ]:
tf_int32 = tf.constant([1,2,3])
tf_int32

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
tf_float32 = tf.constant([1. , 2. , 3.])
tf_float32

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
tf_int16 = tf.cast(tf_int32, dtype=tf.int16)
tf_int16

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 2, 3], dtype=int16)>

In [ ]:
tf_float16 = tf.cast(tf_float32, dtype = tf.float16)
tf_float16

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1., 2., 3.], dtype=float16)>

>> ## **Tensor Aggregation**


In [ ]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([55, 98, 13, 25, 39, 89, 36, 55, 18, 57, 82,  6, 29, 86, 97, 78, 37,
       12, 10,  3, 80, 12, 57, 20, 89, 74, 46, 96, 10, 20, 98, 72,  9, 79,
       65, 23, 24, 88,  2, 14, 57, 40, 37, 31, 99, 34, 70, 31, 35, 84])>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=954.6036>

In [ ]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.89666>

#### IMPORTANT .. 
>>> - What is the difference between positional max and min, and ordinary max and min !

In [ ]:
# create random tensor 
r = tf.random.uniform(shape=[20])
r

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([0.48295116, 0.8671261 , 0.11581647, 0.97698903, 0.49582207,
       0.13357067, 0.7688614 , 0.19136631, 0.01417863, 0.74034345,
       0.1391542 , 0.72758496, 0.45711946, 0.5973216 , 0.92649686,
       0.59118557, 0.89438045, 0.17881203, 0.9413141 , 0.36611676],
      dtype=float32)>

In [ ]:
# its obvious that the max item is 0.9992825 which at index = 7, but we knew that because its very small dataset and we already see it 
## ==> Find position of max item 
tf.argmax(r)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [ ]:
r[tf.argmax(r)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.97698903>

In [ ]:
# we can find the max item, but we can't find its position
tf.math.reduce_max(r)

<tf.Tensor: shape=(), dtype=float32, numpy=0.97698903>

>> ## **One-Hot Encoding**

In [ ]:
tf_text =[5, 4, 8, 3, 2]
tf_text

[5, 4, 8, 3, 2]

In [ ]:
tf_numeric = tf.one_hot(tf_text, depth= np.max(tf_text)+1)
tf_numeric

<tf.Tensor: shape=(5, 9), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
data = [1,2,3,4]
tf.one_hot(data, depth=4, on_value=True, off_value=False)

<tf.Tensor: shape=(4, 4), dtype=bool, numpy=
array([[False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True],
       [False, False, False, False]])>